# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

achr <- function(model, state, warmupPnts, nPnts, stepsPerPnt) {
    .Call('_gembox_achr', PACKAGE = 'gembox', model, state, warmupPnts, nPnts, stepsPerPnt)
}

mepc <- function(model, beta, damp, maxIter, dlb, dub, epsil, ff, fIdx, fMeans, fVars) {
    .Call('_gembox_mepc', PACKAGE = 'gembox', model, beta, damp, maxIter, dlb, dub, epsil, ff, fIdx, fMeans, fVars)
}

